import { get, post, patch } from './base';

// ── Types ────────────────────────────────────────────────────────────────────

export interface ClientPlanningItem {
  id:              number;
  status:          'planned' | 'sent' | 'cancelled' | 'skipped';
  scheduledHeure:  number;
  scheduledMinute: number;
  observation:     string | null;
  canCancel:       boolean;
  alerteAudioId:   number | null;
  audioName:       string | null;
  sireneId:   number;        
  sireneName: string | null; 

}

export interface ClientPlanningSlot {
  date:                 string;
  heure:                number;
  minute:               number;
  estPasse:             boolean;
  estPlein:             boolean;
  dureeCumuleeSecondes: number;
  dureeMaxSecondes:     number;
  items:                ClientPlanningItem[];
}

export interface AudioDisponible {
  id:       number;
  name:     string | null;
  duration: number | null;
}

export interface ClientPlanningResponse {
  souscriptionId:    number;
  sireneId:          number;
  creditsRestants:   number | null;
  nombreCredits:     number | null;
  packName:           string; 
  creneaux:          { heure: number; minute: number }[];
  dureeMaxMinutes:   number;
  audiosDisponibles: AudioDisponible[];
  slots:             ClientPlanningSlot[];
}

export interface ClientAddDiffusionDto {
  souscriptionId: number;
  customerId:     number;
  sireneId:       number;
  alerteAudioId:  number;
  date:           string;
  heure:          number;
}

export interface ClientAddDiffusionResponse {
  id:              number;
  scheduledDate:   string;
  scheduledHeure:  number;
  scheduledMinute: number;
  status:          'planned';
}

export interface GetClientPlanningParams {
  customerId:     number;
  sireneId:      number; 
  souscriptionId: number;
  from:           string;
  to:             string;
}
 

export interface ClientModifyDiffusionDto {
  diffusionId:   number;
  alerteAudioId: number;
  customerId:    number;
}
 
export interface ClientAutoGenerateDto {
  souscriptionId: number;
  customerId:     number;
  sireneId:       number; 
  audioIds:       number[];
}
 
export interface AutoGenerateResult {
  generated: number;
  skipped:   number;
}
 

// ── API object ────────────────────────────────────────────────────────────────

export const diffusionPlanifieeApi = {
  /**
   * GET /diffusion-planifiee/client-planning
   * Retourne le planning d'une sirène pour une semaine,
   * avec disponibilité de chaque créneau et audios disponibles.
   */
  getClientPlanning: (params: GetClientPlanningParams) =>
    get<ClientPlanningResponse>('/diffusion-planifiee/client-planning', { params }),

  /**
   * POST /diffusion-planifiee/client-add
   * Ajoute manuellement une diffusion planifiée.
   * Décrémente 1 crédit sur la souscription.
   * Vérifie que le créneau n'est pas plein et que les crédits sont suffisants.
   */
  clientAdd: (dto: ClientAddDiffusionDto) =>
    post<ClientAddDiffusionResponse>('/diffusion-planifiee/client-add', dto),

  /**
   * PATCH /diffusion-planifiee/:id/cancel
   * Annule une diffusion planifiée (restitue 1 crédit).
   */
  cancel: (id: number, cancelledBy: number) =>
  patch<{ id: number; status: string }>(`/diffusion-planifiee/${id}/cancel`, { cancelledBy }),

  clientModify: (dto: ClientModifyDiffusionDto) =>
  patch<ClientPlanningResponse>('/diffusion-planifiee/client-modify', dto),
  
  clientAutoGenerate: (dto: ClientAutoGenerateDto) =>
    post<AutoGenerateResult>('/diffusion-planifiee/client-auto-generate', dto),
};