export const ROLES = {
    SUPERADMIN:        'SUPERADMIN',
    BNGRC_ALERTE:      'BNGRC_ALERTE',
    CUSTOMER_ADMIN:    'CUSTOMER_ADMIN',
    CUSTOMER_OPERATOR: 'CUSTOMER_OPERATOR',
    BNGRC_CONTROL: 'BNGRC_CONTROL',
} as const;