import { Controller, Get, Post, Body, Patch, Param, Delete, Query, ParseIntPipe } from '@nestjs/common';
import { DiffusionPlanifieeService } from './diffusion-planifiee.service';
import { CreateDiffusionPlanifieeDto } from './dto/create-diffusion-planifiee.dto';
import { UpdateDiffusionPlanifieeDto } from './dto/update-diffusion-planifiee.dto';
import { ClientAddDiffusionDto } from './dto/client-planning.dto';
import { ClientModifyDiffusionDto } from './dto/client-modify-diffusion.dto';
import { ClientAutoGenerateDto } from './dto/client-auto-generate.dto';

@Controller('diffusion-planifiee')
export class DiffusionPlanifieeController {
  constructor(private readonly diffusionPlanifieeService: DiffusionPlanifieeService) {}

  @Get('client-planning')
  getClientPlanning(
    @Query('customerId')     customerIdStr:     string,
    @Query('souscriptionId') souscriptionIdStr: string,
    @Query('from')           from:              string,
    @Query('to')             to:                string,
    @Query('sireneId')       sireneIdStr?:      string,
  ) {
    const customerId     = Number(customerIdStr);
    const souscriptionId = Number(souscriptionIdStr);
    const sireneId       =  Number(sireneIdStr) ;

    return this.diffusionPlanifieeService.getClientPlanning({ customerId, sireneId, souscriptionId, from, to });
  }

  @Patch(':id/cancel')
  cancel(@Param('id', ParseIntPipe) id: number, @Body('cancelledBy') cancelledBy: number, ) {
    return this.diffusionPlanifieeService.cancel(id, cancelledBy);
  }
  
  // POST /diffusion-planifiee/client-add
  @Post('client-add')
  clientAddDiffusion(@Body() dto: ClientAddDiffusionDto) {
    return this.diffusionPlanifieeService.clientAddDiffusion(dto);
  }
  
  @Patch('client-modify')
  clientModifyDiffusion(@Body() dto: ClientModifyDiffusionDto) {
    return this.diffusionPlanifieeService.clientModifyDiffusion(dto);
  }

  @Post('client-auto-generate')
  clientAutoGenerate(@Body() dto: ClientAutoGenerateDto) {
    return this.diffusionPlanifieeService.clientAutoGenerate(dto);
  }

  // @Post()
  // create(@Body() createDiffusionPlanifieeDto: CreateDiffusionPlanifieeDto) {
  //   return this.diffusionPlanifieeService.create(createDiffusionPlanifieeDto);
  // }

  // @Get()
  // findAll() {
  //   return this.diffusionPlanifieeService.findAll();
  // }

  // @Get(':id')
  // findOne(@Param('id') id: string) {
  //   return this.diffusionPlanifieeService.findOne(+id);
  // }

  // @Patch(':id')
  // update(@Param('id') id: string, @Body() updateDiffusionPlanifieeDto: UpdateDiffusionPlanifieeDto) {
  //   return this.diffusionPlanifieeService.update(+id, updateDiffusionPlanifieeDto);
  // }

  // @Delete(':id')
  // remove(@Param('id') id: string) {
  //   return this.diffusionPlanifieeService.remove(+id);
  // }
}
